id: kCqqHO7DPCv2sgKo9LKH
version: 0.0.20
auths: {}
hasData: false
safety: true
public: true
name: Chart
lastSave: 1570899302794
providerId: snapboard
inputs:
  fields:
    - title: Chart Type
      key: type
      prop: type
      default: Bar
      options:
        selectOptions: [Bar, Line, Doughnut, Funnel, Radar]
      type: select
    - title: Chart Data
      key: data
      prop: data
      type: text
      required: true
      caption: >-
        Data your chart - <a href="#"
        data-beacon-article="5da1d0b62c7d3a7e9ae26d96">learn how to format
        card</a>
    - prop: labels
      title: Labels
      multi: true
      key: labels
      type: text
