id: kCqqHO7DPCv2sgKo9LKH
version: 0.0.18
auths: {}
hasData: false
safety: true
public: true
name: Chart
lastSave: 1570899302794
providerId: snapboard
inputs:
  fields:
    - title: Chart Data
      key: data
      prop: data
      type: text
      required: true
      caption: >-
        Data your chart - [learn how to format
        here](https://help.snapboard.io/article/12-intro-value-types)
    - prop: labels
      title: Labels
      multi: true
      key: labels
      type: text
