id: kCqqHO7DPCv2sgKo9LKH
version: 0.0.34
auths: {}
hasData: false
safety: true
public: true
name: Chart
lastSave: 1570899302794
providerId: snapboard
inputs:
  derived:
    xaxis: =$inputs.data.xaxis
    period: =$inputs.data.period
    data: |-
      =Switch(
        $inputs.data.xaxis,
        'auto', $inputs.data.source,
        'date', (
          Switch(
            $inputs.data.yaxis,
            'count', (
              CountByGroup(
                Filter(
                  $inputs.data.source,
                  IsWithin(ToDate(Get($value, $inputs.data.date)), $inputs.data.period.count, $inputs.data.period.unit)
                ),
                If($inputs.data.groupby, StartOf(Get($value, $inputs.data.date), $inputs.data.period.unit) & '.' & Get($value, $inputs.data.groupby), StartOf(Get($value, $inputs.data.date), $inputs.data.period.unit))
              )
            ),
            'sum', (
              SumByGroup(
                Filter(
                  $inputs.data.source,
                  IsWithin(ToDate(Get($value, $inputs.data.date)), $inputs.data.period.count, $inputs.data.period.unit)
                ),
                If($inputs.data.groupby, StartOf(Get($value, $inputs.data.date), $inputs.data.period.unit) & '.' & Get($value, $inputs.data.groupby), StartOf(Get($value, $inputs.data.date), $inputs.data.period.unit)),
                $inputs.data.aggregate
              )
            ),
            'min', (
              MinByGroup(
                Filter(
                  $inputs.data.source,
                  IsWithin(ToDate(Get($value, $inputs.data.date)), $inputs.data.period.count, $inputs.data.period.unit)
                ),
                If($inputs.data.groupby, StartOf(Get($value, $inputs.data.date), $inputs.data.period.unit) & '.' & Get($value, $inputs.data.groupby), StartOf(Get($value, $inputs.data.date), $inputs.data.period.unit)),
                $inputs.data.aggregate
              )
            ),
            'max', (
              MaxByGroup(
                Filter(
                  $inputs.data.source,
                  IsWithin(ToDate(Get($value, $inputs.data.date)), $inputs.data.period.count, $inputs.data.period.unit)
                ),
                If($inputs.data.groupby, StartOf(Get($value, $inputs.data.date), $inputs.data.period.unit) & '.' & Get($value, $inputs.data.groupby), StartOf(Get($value, $inputs.data.date), $inputs.data.period.unit)),
                $inputs.data.aggregate
              )
            )
          )
        )
      )
  fields:
    - title: Chart Type
      key: type
      prop: type
      default: bar
      options:
        selectOptions:
          - label: Bar
            value: bar
          - label: Line
            value: line
          - label: Doughnut
            value: doughnut
          - label: Funnel
            value: funnel
          - label: Radar
            value: radar
      type: select
  tabs:
    data:
      title: Data
      fields:
        source:
          type: formula
          title: Source
          caption: 'A reference, hash or list of data'
          required: true
        xaxis:
          type: select
          title: X-Axis
          default: auto
          options:
            selectOptions:
              - label: Auto
                value: auto
              - label: Date
                value: date
          switch:
            auto:
              fields:
                labels:
                  title: Labels
                  multi: true
                  type: text
            date:
              fields:
                - prop: period
                  title: Period
                  type: inline
                  required: true
                  options:
                    widths:
                      - 20
                      - 80
                  fields:
                    count:
                      title: Count
                      type: text
                      placeholder: No.
                      default: '14'
                    unit:
                      title: Period
                      type: select
                      placeholder: Select a time period...
                      default: day
                      options:
                        selectOptions:
                          - label: Minutes
                            value: minute
                          - label: Hours
                            value: hour
                          - label: Days
                            value: day
                          - label: Weeks
                            value: week
                          - label: Months
                            value: month
                          - label: Quaters
                            value: quater
                          - label: Years
                            value: year
                - prop: date
                  title: Date Field
                  type: text
                  placeholder: Name of field
                  caption: The name of the field in source to use as the date
                - prop: yaxis
                  title: Y-Axis
                  type: select
                  placeholder: Select aggregation type
                  default: count
                  options:
                    selectOptions:
                      - label: Count
                        value: count
                      - label: Sum
                        value: sum
                      - label: Min
                        value: min
                      - label: Max
                        value: max
                  switch:
                    count: {}
                    sum:
                      fields:
                        aggregate:
                          title: Sum Field
                          type: text
                          placeholder: Name of field
                          caption: >-
                            Formula is calculated for every row in `Source` (you
                            can use any fields in source). Each row's output is
                            added together.
                    min:
                      fields:
                        aggregate:
                          title: Min Field
                          type: text
                          placeholder: Name of field
                          caption: >-
                            Formula is calculated for every row in `Source` (you
                            can use any fields in source). Each row's output is
                            compared, and the smallest row value is used.
                    max:
                      fields:
                        aggregate:
                          title: Max Field
                          type: text
                          placeholder: Name of field
                          caption: >-
                            Formula is calculated for every row in `Source` (you
                            can use any fields in source). Each row's output is
                            compared, and the largest row value is used.
                - prop: groupby
                  title: GroupBy
                  type: text
                  placeholder: Name of field
                  caption: >-
                    Formula is calculated for every row in `Source` (you can use
                    any fields in source).
