id: kCqqHO7DPCv2sgKo9LKH
version: 0.0.29
auths: {}
hasData: false
safety: true
public: true
name: Chart
lastSave: 1570899302794
providerId: snapboard
inputs:
  derived:
    xaxis: =$inputs.data.xaxis
    period: =$inputs.data.period
    data: |-
      =Stash(
        '$date',
        If(IsFormula($inputs.data.date), $inputs.data.date, Get($value, $inputs.data.date)),
        Stash(
          '$groupby',
          If($inputs.data.groupby, StartOf($date, $inputs.data.period.unit) & '.' & If(IsFormula($inputs.data.groupby), $inputs.data.groupby, Get($value, $inputs.data.groupby)), StartOf($date, $inputs.data.period.unit)),
          Switch(
            $inputs.data.xaxis,
            'auto', $inputs.data.source,
            'date', (
              Switch(
                $inputs.data.yaxis,
                'count', (
                  CountByGroup(
                    Filter(
                      $inputs.data.source,
                      IsWithin($date, $inputs.data.period.count, $inputs.data.period.unit)
                    ),
                    $groupby
                  )
                ),
                'sum', (
                  SumByGroup(
                    Filter(
                      $inputs.data.source,
                      IsWithin($date, $inputs.data.period.count, $inputs.data.period.unit)
                    ),
                    $groupby,
                    $inputs.data.aggregate
                  )
                ),
                'min', (
                  MinByGroup(
                    Filter(
                      $inputs.data.source,
                      IsWithin($date, $inputs.data.period.count, $inputs.data.period.unit)
                    ),
                    $groupby,
                    $inputs.data.aggregate
                  )
                ),
                'max', (
                  MaxByGroup(
                    Filter(
                      $inputs.data.source,
                      IsWithin($date, $inputs.data.period.count, $inputs.data.period.unit)
                    ),
                    $groupby,
                    $inputs.data.aggregate
                  )
                )
              )
            )
          )
        )
      )
  fields:
    - title: Chart Type
      key: type
      prop: type
      defaultValue: bar
      options:
        selectOptions:
          - label: Bar
            value: bar
          - label: Line
            value: line
          - label: Doughnut
            value: doughnut
          - label: Funnel
            value: funnel
          - label: Radar
            value: radar
      type: select
  tabs:
    data:
      title: Data
      fields:
        source:
          type: formula
          title: Source
          caption: 'A reference, hash or list of data'
          required: true
        xaxis:
          type: select
          title: X-Axis
          defaultValue: auto
          options:
            selectOptions:
              - label: Auto
                value: auto
              - label: Date
                value: date
          switch:
            auto:
              fields:
                labels:
                  title: Labels
                  multi: true
                  type: text
            date:
              fields:
                - prop: period
                  title: Period
                  type: inline
                  required: true
                  options:
                    widths:
                      - 20
                      - 80
                  fields:
                    count:
                      title: Count
                      type: text
                      placeholder: No.
                      defaultValue: '14'
                    unit:
                      title: Period
                      type: select
                      placeholder: Select a time period...
                      defaultValue: day
                      options:
                        selectOptions:
                          - label: Minutes
                            value: minute
                          - label: Hours
                            value: hour
                          - label: Days
                            value: day
                          - label: Weeks
                            value: week
                          - label: Months
                            value: month
                          - label: Quaters
                            value: quater
                          - label: Years
                            value: year
                - prop: date
                  title: Date Field
                  type: text
                  placeholder: Name of field
                  caption: >-
                    The name of the field in `Source` to use as the date, or a
                    formula that returns a date.
                - prop: yaxis
                  title: Y-Axis
                  type: select
                  placeholder: Select aggregation type
                  caption: >-
                    When we group values in `Source` by date, how should we
                    combine their value.
                  defaultValue: count
                  options:
                    selectOptions:
                      - label: Count
                        value: count
                      - label: Sum
                        value: sum
                      - label: Min
                        value: min
                      - label: Max
                        value: max
                  switch:
                    count: {}
                    sum:
                      fields:
                        aggregate:
                          title: Sum Field
                          type: text
                          placeholder: Name of field
                          caption: >-
                            Formula is calculated for every row in `Source` (you
                            can use any fields in `Source`). Each row's output
                            is added together.
                    min:
                      fields:
                        aggregate:
                          title: Min Field
                          type: text
                          placeholder: Name of field
                          caption: >-
                            Formula is calculated for every row in `Source` (you
                            can use any fields in source). Each row's output is
                            compared, and the smallest row value is used.
                    max:
                      fields:
                        aggregate:
                          title: Max Field
                          type: text
                          placeholder: Name of field
                          caption: >-
                            Formula is calculated for every row in `Source` (you
                            can use any fields in source). Each row's output is
                            compared, and the largest row value is used.
                - prop: groupby
                  title: GroupBy
                  type: text
                  placeholder: Name of field
                  caption: >-
                    Formula is calculated for every row in `Source` (you can use
                    any fields in source).
